version: '3.5'
services:
    database:
        image: mysql
        container_name: work1
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        ports:
            - "3333:3306"
        environment:
            MYSQL_ROOT_PASSWORD: 123456
        volumes:
          -  './volumemysql:/var/lib/mysql'
          -  './schema.sql:/docker-entrypoint-initdb.d/schema.sql'

    adminer:
      image: adminer
      restart: always
      ports:
        - 8080:8080